### ISSUE TITLE
problem installing bundle in Pimcore 11

### ISSUE THREAD

**Issue by digital-transformers** [syncrasy-git/Pimcore-Salesforce-Connector#3]
trying to run command 

php bin/console pimcore:bundle:install SyncrasyPimcoreSalesforceBundle

i get the following error:

PHP Fatal error:  Declaration of Syncrasy\PimcoreSalesforceBundle\SyncrasyPimcoreSalesforceBundle::getNiceName() must be compatible with Pimcore\Extension\Bundle\AbstractPimcoreBundle::getNiceName(): string in /var/www/html/vendor/syncrasy/pimcore-salesforce-bundle/SyncrasyPimcoreSalesforceBundle.php on line 46

Pimcore version: 11.0.7

**Comment by syncrasy-git** [comment]
Pimcore - Salesforce Connector doe not support Pimcore 11.x yet. Please try this bundle with Pimcore 10.x.
